/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedPanoramaRouteImport } from './routes/_authenticated/panorama'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedLaborRouteImport } from './routes/_authenticated/labor'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGroundwaterRouteImport } from './routes/_authenticated/groundwater'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated/diagnostics'
import { Route as AuthenticatedAuditsRouteImport } from './routes/_authenticated/audits'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanoramaRoute = AuthenticatedPanoramaRouteImport.update({
  id: '/panorama',
  path: '/panorama',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaborRoute = AuthenticatedLaborRouteImport.update({
  id: '/labor',
  path: '/labor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroundwaterRoute =
  AuthenticatedGroundwaterRouteImport.update({
    id: '/groundwater',
    path: '/groundwater',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditsRoute = AuthenticatedAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audits': typeof AuthenticatedAuditsRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/groundwater': typeof AuthenticatedGroundwaterRoute
  '/home': typeof AuthenticatedHomeRoute
  '/labor': typeof AuthenticatedLaborRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/panorama': typeof AuthenticatedPanoramaRoute
  '/progress': typeof AuthenticatedProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audits': typeof AuthenticatedAuditsRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/groundwater': typeof AuthenticatedGroundwaterRoute
  '/home': typeof AuthenticatedHomeRoute
  '/labor': typeof AuthenticatedLaborRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/panorama': typeof AuthenticatedPanoramaRoute
  '/progress': typeof AuthenticatedProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audits': typeof AuthenticatedAuditsRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/groundwater': typeof AuthenticatedGroundwaterRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/labor': typeof AuthenticatedLaborRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/panorama': typeof AuthenticatedPanoramaRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audits'
    | '/diagnostics'
    | '/groundwater'
    | '/home'
    | '/labor'
    | '/materials'
    | '/panorama'
    | '/progress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audits'
    | '/diagnostics'
    | '/groundwater'
    | '/home'
    | '/labor'
    | '/materials'
    | '/panorama'
    | '/progress'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audits'
    | '/_authenticated/diagnostics'
    | '/_authenticated/groundwater'
    | '/_authenticated/home'
    | '/_authenticated/labor'
    | '/_authenticated/materials'
    | '/_authenticated/panorama'
    | '/_authenticated/progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panorama': {
      id: '/_authenticated/panorama'
      path: '/panorama'
      fullPath: '/panorama'
      preLoaderRoute: typeof AuthenticatedPanoramaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labor': {
      id: '/_authenticated/labor'
      path: '/labor'
      fullPath: '/labor'
      preLoaderRoute: typeof AuthenticatedLaborRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groundwater': {
      id: '/_authenticated/groundwater'
      path: '/groundwater'
      fullPath: '/groundwater'
      preLoaderRoute: typeof AuthenticatedGroundwaterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audits': {
      id: '/_authenticated/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuthenticatedAuditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditsRoute: typeof AuthenticatedAuditsRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedGroundwaterRoute: typeof AuthenticatedGroundwaterRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLaborRoute: typeof AuthenticatedLaborRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedPanoramaRoute: typeof AuthenticatedPanoramaRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditsRoute: AuthenticatedAuditsRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedGroundwaterRoute: AuthenticatedGroundwaterRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLaborRoute: AuthenticatedLaborRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedPanoramaRoute: AuthenticatedPanoramaRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
